const firebaseAuthErrorCodes: any = {
  'auth/weak-password': 'Senha fraca, digite pelo menos 6 caracteres!',
  'auth/timeout': 'Tempo limite excedido!',
  'auth/admin-restricted-operation': 'Operação reservada a administradores!',
  'auth/code-expired': 'Código de autenticação expirado!',
  'auth/cors-unsupported': 'Erro na politica de cors!',
  'auth/credential-already-in-use': 'Credenciais já em uso em outro lugar/máquina!',
  'auth/email-already-in-use': 'Email já está em uso!',
  'auth/internal-error': 'Erro interno da aplicação de autenticação!',
  'auth/invalid-api-key': 'Chave da api de autenticação inválida!',
  'auth/invalid-user-token': 'Token inválido!',
  'auth/invalid-verification-code': 'Código de verificação inválido!',
  'auth/invalid-email': 'Email inválido!',
  'auth/invalid-credential': 'Credenciais inválidas!',
  'auth/wrong-password': 'Credenciais incorretas!',
  'auth/invalid-phone-number': 'Número de celular inválida!',
  'auth/missing-verification-code': 'Código de verificação faltando!',
  'auth/missing-phone-number': 'Número de celular faltando!',
  'auth/account-exists-with-different-credential': 'Credenciais inválidas!',
  'auth/operation-not-allowed': 'Operação não permitida!',
  'auth/rejected-credential': 'Credenciais negadas!',
  'auth/user-token-expired': 'Token de autenticação expirado!',
  'auth/too-many-requests': 'Muitas tentativas em pouco tempo, aguarde alguns minutos antes de tentar novamente!',
  'auth/unverified-email': 'Email não verificado!',
  'auth/user-not-found': 'Usuário não encontrado!',
  'auth/user-disabled': 'Usuário desabilitado!',
  'auth/user-signed-out': 'Usuário deslogado!',
  'auth/already-initialized': 'Sessão já iniciada!'
}

export default firebaseAuthErrorCodes
